name: voicepals
description: A new Flutter project.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  supabase_flutter: ^1.9.1
  # uni_links: ^0.5.1
  rive: ^0.11.0
  delayed_widget: ^1.1.2
  cached_network_image: ^3.2.3
  animated_bottom_navigation_bar: ^1.2.0

  get: ^4.6.5
  flutter_spinkit: ^5.2.0
  responsive_framework: ^1.0.0
  flutter_datetime_picker: ^1.5.1
  google_fonts: ^4.0.4
  anim_search_bar: ^2.0.3
  timeago: ^3.4.0
  image_picker: ^0.8.7+5
  record: ^4.4.4
  focused_menu_custom: ^1.2.0
  animated_text_kit: ^4.2.2
  easy_refresh: ^3.3.2+1

  dotted_border: ^2.0.0+3
  shimmer: ^3.0.0

  uuid: ^3.0.7
  siri_wave: ^0.3.0
  lucide_icons: ^0.220.0
  flutter_slidable: ^3.0.0
  octo_image: ^1.0.2
  video_player: ^2.6.1
  gallery_saver: ^2.3.2
      

  voice_message_package:
    git: 
      url: https://github.com/sasen98/voice_message_player.git
  flutter_vibrate: ^1.3.0
     

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/animations/kcSwitch.riv
    - assets/animations/kcBlooming.riv
    - assets/animations/kcEmptyState.gif
    - assets/animations/kcEmpty.jpg
    - assets/socials/github.png
    - assets/socials/facebook.png
    - assets/socials/linkedin.png
    - assets/socials/apple.png
    - assets/socials/github_glyph.png
    - assets/socials/facebook_glyph.png
    - assets/socials/linkedin_glyph.png
    - assets/socials/apple_glyph.png
    - assets/kcLanding.jpeg
    - assets/kcProfileBg.png
    - assets/kcTrial.gif
    - assets/animations/kcEmptyState.png
    - shorebird.yaml
